version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            export SPRING_APPLICATION_NAME="app"
            export SPRING_SECURITY_SECRET="${SPRING_SECURITY_SECRET}"
            export SPRING_DATA_MONGODB_URI="${SPRING_DATA_MONGODB_URI}"
            export SPRING_DATA_MONGODB_DATABASE="${SPRING_DATA_MONGODB_DATABASE}"
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn clean install
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '# Replace this with your deploy script, e.g., ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-java
